[package]
name = "calculator"
version = "0.1.0"
authors = ["Charles Bayley <cbayley95@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
regex = "1.4.4"
float-cmp = "0.9.0"
